# File: .github/workflows/workflow.yml
on: [push]

name: example

jobs:


  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        name: mytest_picarenlamina
    
    - name: "Build"
      uses: okteto/build@latest
